import type { SeedStand } from "./types";

export const SEED_STANDS: SeedStand[] = [
  {
    id: "casa-pan",
    name: "Casa Pan",
    kind: "bakery",
    access: "walk-up",
    county: "Pinellas",
    city: "Palm Harbor",
    address: "2196 Orangeside Rd",
    zip: null,
    lat: 28.087964468659,
    lng: -82.742947455945,
    pinQuality: "exact",
    hours: "Wed–Sun 8am–dark",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["bread", "cookies", "jam", "baked goods"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "the-daily-rise",
    name: "The Daily Rise",
    kind: "bakery",
    access: "walk-up",
    county: "Pinellas",
    city: "Palm Harbor",
    address: "311 19th St",
    zip: null,
    lat: 28.070169786159,
    lng: -82.751633114548,
    pinQuality: "exact",
    hours: "Sun 10am–1pm",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["bread", "baked goods", "pastries"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "sarah-sourdough",
    name: "Sarah + Sourdough",
    kind: "bakery",
    access: "check-page",
    county: "Pinellas",
    city: "Palm Harbor",
    address: "995 Lakeview Dr",
    zip: null,
    lat: 28.092110369271,
    lng: -82.756862744798,
    pinQuality: "exact",
    hours: "Check page for schedule",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["bread", "cupcakes", "cookies", "donuts"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "r-r-microbakery",
    name: "R&R Microbakery",
    kind: "bakery",
    access: "preorder",
    county: "Pinellas",
    city: "Palm Harbor",
    address: "3000 Jodi Ln",
    zip: null,
    lat: 28.097900071436,
    lng: -82.729904064225,
    pinQuality: "exact",
    hours: "Msg for preorder",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["bread", "bagels", "cookies", "cake"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "the-sassy-crumb",
    name: "The Sassy Crumb",
    kind: "bakery",
    access: "preorder",
    county: "Pinellas",
    city: "Palm Harbor",
    address: "638 Sedgwick Way",
    zip: null,
    lat: 28.05912641529,
    lng: -82.744184938942,
    pinQuality: "exact",
    hours: "Msg for preorder",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["bread", "bagels"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "storybook-macarons",
    name: "Storybook Macarons",
    kind: "bakery",
    access: "preorder",
    county: "Pinellas",
    city: "Palm Harbor",
    address: null,
    zip: null,
    lat: 28.071517,
    lng: -82.7697,
    pinQuality: "approx",
    hours: "Msg for preorder",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["macarons", "sweets"],
    notes: "No public street address in source list.",
    sourceNotes: null,
    featured: false,
  },
  {
    id: "la-tea-dough-sourdough",
    name: "La Tea Dough Sourdough",
    kind: "bakery",
    access: "preorder",
    county: "Pinellas",
    city: "Palm Harbor",
    address: null,
    zip: null,
    lat: 28.079683,
    lng: -82.762867,
    pinQuality: "approx",
    hours: "Msg for address and preorder",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["bread", "bagels", "cookies"],
    notes: "Address shared on request.",
    sourceNotes: null,
    featured: false,
  },
  {
    id: "sweet-savory-sourdough",
    name: "Sweet, Savory & Sourdough",
    kind: "bakery",
    access: "preorder",
    county: "Pinellas",
    city: "Crystal Beach",
    address: "230 Georgia Ave",
    zip: null,
    lat: 28.086290264873,
    lng: -82.775414665587,
    pinQuality: "exact",
    hours: "Msg for preorder",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["bread", "cake", "cookies", "cupcakes"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "baking-by-the-sea",
    name: "Baking By The Sea",
    kind: "bakery",
    access: "check-page",
    county: "Pinellas",
    city: "Dunedin",
    address: "Main St & Broadway",
    zip: null,
    lat: 28.0182,
    lng: -82.764383,
    pinQuality: "approx",
    hours: "Check page for schedule",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["bread", "cookies", "cake", "cupcakes"],
    notes: "Corner of Main and Broadway.",
    sourceNotes: null,
    featured: false,
  },
  {
    id: "dough-kneadin",
    name: "Dough-Kneadin'",
    kind: "bakery",
    access: "preorder",
    county: "Pinellas",
    city: "Dunedin",
    address: null,
    zip: null,
    lat: 28.0197,
    lng: -82.777967,
    pinQuality: "approx",
    hours: "Msg for preorder",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["bread", "cookies"],
    notes: "Markets around Dunedin.",
    sourceNotes: null,
    featured: false,
  },
  {
    id: "grazia-s-goodies-sourdough-and-sweets",
    name: "Grazia's Goodies Sourdough and Sweets",
    kind: "bakery",
    access: "preorder",
    county: "Pinellas",
    city: "Safety Harbor",
    address: null,
    zip: null,
    lat: 27.992483,
    lng: -82.690033,
    pinQuality: "approx",
    hours: "Msg for preorder or local delivery",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["bread", "cookies", "sweets"],
    notes: "Offers local delivery.",
    sourceNotes: null,
    featured: false,
  },
  {
    id: "southern-sunshine-farms",
    name: "Southern Sunshine Farms",
    kind: "stand",
    access: "walk-up",
    county: "Pasco",
    city: "Hudson",
    address: "15232 Matis Rd",
    zip: null,
    lat: 28.380879411034,
    lng: -82.625145046639,
    pinQuality: "exact",
    hours: "Tue–Fri 10am–6pm, Sat 9am–1pm",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["produce", "berries", "cheese", "eggs", "milk", "honey", "jam"],
    notes: null,
    sourceNotes: null,
    featured: true,
  },
  {
    id: "kneady-batch-home-bakery",
    name: "Kneady Batch Home Bakery",
    kind: "bakery",
    access: "walk-up",
    county: "Pasco",
    city: "Hudson",
    address: "10043 Carl St",
    zip: null,
    lat: 28.346200032748,
    lng: -82.64819308284,
    pinQuality: "exact",
    hours: "Fri/Sat 9am–sellout",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["bread", "pastries", "donuts", "cake", "cookies"],
    notes: "Sells out.",
    sourceNotes: null,
    featured: false,
  },
  {
    id: "duck-you-coffee-boosted-beverages",
    name: "Duck You Coffee / Boosted Beverages",
    kind: "market",
    access: "markets",
    county: "Pasco",
    city: "Hudson",
    address: null,
    zip: null,
    lat: 28.36765,
    lng: -82.687067,
    pinQuality: "approx",
    hours: "Check page for schedule",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["coffee", "drinks"],
    notes: "Markets around Hudson.",
    sourceNotes: null,
    featured: false,
  },
  {
    id: "keystone-farmers-market",
    name: "Keystone Farmers Market",
    kind: "market",
    access: "walk-up",
    county: "Hillsborough",
    city: "Odessa",
    address: "12615 Tarpon Springs Rd",
    zip: null,
    lat: 28.140573081988,
    lng: -82.638407981273,
    pinQuality: "exact",
    hours: "Mon–Fri 8am–6:30pm, Sat/Sun 8am–6pm",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["produce", "market"],
    notes: "Retail market, not a single-farm stand.",
    sourceNotes: null,
    featured: false,
  },
  {
    id: "caroline-s-confections",
    name: "Caroline's Confections",
    kind: "bakery",
    access: "walk-up",
    county: "Hillsborough",
    city: "Odessa",
    address: "14214 Chisholm Ln",
    zip: null,
    lat: 28.180254631948,
    lng: -82.581130109525,
    pinQuality: "exact",
    hours: "Fri 3pm–dark, Sat/Sun 9am–dark",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["cookies", "cake", "bread"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "simply-sourdough-starkey-ranch",
    name: "Simply Sourdough — Starkey Ranch",
    kind: "bakery",
    access: "preorder",
    county: "Pasco",
    city: "Odessa",
    address: "13745 Stansil Ave",
    zip: null,
    lat: 28.201063762042,
    lng: -82.588852472462,
    pinQuality: "exact",
    hours: "Msg for preorder",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["bread", "pretzels"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "full-table-bakes",
    name: "Full Table Bakes",
    kind: "bakery",
    access: "walk-up",
    county: "Hillsborough",
    city: "Odessa",
    address: "13127 Burns Dr",
    zip: null,
    lat: 28.194439963432,
    lng: -82.60137841465,
    pinQuality: "exact",
    hours: "7 days, hours vary",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["cookies", "bread"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "purple-door-confections",
    name: "Purple Door Confections",
    kind: "bakery",
    access: "preorder",
    county: "Hillsborough",
    city: "Citrus Park",
    address: null,
    zip: null,
    lat: 28.07185,
    lng: -82.5731,
    pinQuality: "approx",
    hours: "Msg for preorder",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["cake", "sweets", "pretzels"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "little-bitez",
    name: "Little Bitez",
    kind: "bakery",
    access: "walk-up",
    county: "Pinellas",
    city: "Clearwater",
    address: "2860 Meadow Hill Dr N",
    zip: null,
    lat: 28.030545200268,
    lng: -82.720792830915,
    pinQuality: "exact",
    hours: "Sat–Sun 8am–11am",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["cookies", "bread", "sweets"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "southern-biophilliac",
    name: "Southern Biophilliac",
    kind: "stand",
    access: "check-page",
    county: "Pinellas",
    city: "Pinellas Park",
    address: "102nd Ave N",
    zip: null,
    lat: 27.8463,
    lng: -82.702917,
    pinQuality: "approx",
    hours: "Check for hours",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["produce", "berries", "eggs", "honey", "plants"],
    notes: "Street number not listed.",
    sourceNotes: null,
    featured: false,
  },
  {
    id: "sarah-s-simply-sourdough",
    name: "Sarah's Simply Sourdough",
    kind: "bakery",
    access: "preorder",
    county: "Pasco",
    city: "Holiday",
    address: null,
    zip: null,
    lat: 28.191467,
    lng: -82.732583,
    pinQuality: "approx",
    hours: "Msg for preorder",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["bread", "bagels"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "jenny-s-sourdough-bread",
    name: "Jenny's Sourdough Bread",
    kind: "bakery",
    access: "preorder",
    county: "Pasco",
    city: "Holiday",
    address: null,
    zip: null,
    lat: 28.192133,
    lng: -82.74525,
    pinQuality: "approx",
    hours: "Msg for preorder",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["bread", "bagels", "cookies"],
    notes: "Holiday / Carrollwood.",
    sourceNotes: null,
    featured: false,
  },
  {
    id: "joyful-chirpy-chic-s-chicken-haven",
    name: "Joyful Chirpy Chic's Chicken Haven",
    kind: "market",
    access: "markets",
    county: "Pasco",
    city: "Holiday",
    address: null,
    zip: null,
    lat: 28.1883,
    lng: -82.746417,
    pinQuality: "approx",
    hours: "Check page for schedule",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["eggs", "soap", "cookies"],
    notes: "Markets around town.",
    sourceNotes: null,
    featured: false,
  },
  {
    id: "the-sticky-bun",
    name: "The Sticky Bun",
    kind: "bakery",
    access: "walk-up",
    county: "Pasco",
    city: "New Port Richey",
    address: "8724 Gum Tree Ave",
    zip: null,
    lat: 28.223883471259,
    lng: -82.670120941095,
    pinQuality: "exact",
    hours: "Thu–Sat 8am–6pm",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["cookies", "sweets"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "elise-s-sweet-life",
    name: "Elise's Sweet Life",
    kind: "bakery",
    access: "check-page",
    county: "Pasco",
    city: "New Port Richey",
    address: "3531 Hunting Creek Loop",
    zip: null,
    lat: 28.208992809646,
    lng: -82.674725267897,
    pinQuality: "exact",
    hours: "Check page for pop-ups",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["cookies", "cake", "sweets"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "nancy-s-fancy-plants-more",
    name: "Nancy's Fancy Plants & More",
    kind: "market",
    access: "markets",
    county: "Pasco",
    city: "New Port Richey",
    address: "8502 Adonis Rd",
    zip: null,
    lat: 28.282410457327,
    lng: -82.674316613604,
    pinQuality: "exact",
    hours: "Tasty Tuesday Market, downtown NPR",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["eggs", "plants", "drinks", "preserves"],
    notes: "Also at Tasty Tuesday downtown NPR.",
    sourceNotes: null,
    featured: false,
  },
  {
    id: "green-harvest-haven",
    name: "Green Harvest Haven",
    kind: "stand",
    access: "walk-up",
    county: "Pasco",
    city: "New Port Richey",
    address: "9215 Ridge Rd",
    zip: null,
    lat: 28.280660726961,
    lng: -82.663241680972,
    pinQuality: "exact",
    hours: "Mon–Sat 10am–6pm, Sun 10am–4pm",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["produce", "berries", "fruit"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "the-honey-couple",
    name: "The Honey Couple",
    kind: "stand",
    access: "walk-up",
    county: "Pasco",
    city: "New Port Richey",
    address: "8045 Hutchinson Dr",
    zip: null,
    lat: 28.27192305143,
    lng: -82.681597120068,
    pinQuality: "exact",
    hours: "24/7 self-serve",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["honey", "chili", "flowers"],
    notes: "Honor-system stand.",
    sourceNotes: null,
    featured: false,
  },
  {
    id: "bacon-bread-boutique",
    name: "Bacon Bread Boutique",
    kind: "bakery",
    access: "check-page",
    county: "Pasco",
    city: "New Port Richey",
    address: "7718 Eglantine Ln",
    zip: null,
    lat: 28.26942726992,
    lng: -82.616325700995,
    pinQuality: "exact",
    hours: "Check page for pop-ups",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["bread"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "talk-sweets-to-me",
    name: "Talk Sweets To Me",
    kind: "bakery",
    access: "walk-up",
    county: "Pasco",
    city: "Port Richey",
    address: "Glen Moor Ln",
    zip: null,
    lat: 28.279533,
    lng: -82.716,
    pinQuality: "approx",
    hours: "Fri/Sat 9am–sellout",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["cake", "sweets", "pretzels"],
    notes: "Street number not listed.",
    sourceNotes: null,
    featured: false,
  },
  {
    id: "flock-flour-bakery",
    name: "Flock & Flour Bakery",
    kind: "bakery",
    access: "walk-up",
    county: "Pasco",
    city: "New Port Richey",
    address: "9616 Casey Dr",
    zip: null,
    lat: 28.298643466031,
    lng: -82.65185003051,
    pinQuality: "exact",
    hours: "Sat/Sun 9am–8pm",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["cookies", "bread", "cupcakes", "eggs"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "crust-and-crumb-artisan-sourdough",
    name: "Crust and Crumb Artisan Sourdough",
    kind: "bakery",
    access: "walk-up",
    county: "Pasco",
    city: "New Port Richey",
    address: "10645 Aphrodite Loop",
    zip: null,
    lat: 28.328677352426,
    lng: -82.638669124713,
    pinQuality: "exact",
    hours: "Sun 9am–sellout",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["bread", "cookies", "bagels", "cupcakes"],
    notes: "Sells out.",
    sourceNotes: null,
    featured: false,
  },
  {
    id: "the-storehouse",
    name: "The Storehouse",
    kind: "bakery",
    access: "walk-up",
    county: "Pasco",
    city: "New Port Richey",
    address: "10650 Fawn Dr",
    zip: "34654",
    lat: 28.321344447064,
    lng: -82.638907857412,
    pinQuality: "exact",
    hours: "Fri/Sat 9am–5pm",
    phone: null,
    email: null,
    website: null,
    facebook: "https://www.facebook.com/people/The-Storehouse/61588233880904/",
    instagram: "https://www.instagram.com/storehousestand/",
    products: ["bread", "cake", "cookies", "pretzels", "cupcakes", "coffee"],
    notes: null,
    sourceNotes: "Instagram @storehousestand.",
    featured: true,
  },
  {
    id: "the-organic-guys",
    name: "The Organic Guys",
    kind: "stand",
    access: "walk-up",
    county: "Pasco",
    city: "New Port Richey",
    address: "11730 Chipley St",
    zip: null,
    lat: 28.327929859899,
    lng: -82.608928380749,
    pinQuality: "exact",
    hours: "Sat 9am–5pm",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["produce", "plants"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "the-sugar-shack-farmstand",
    name: "The Sugar Shack Farmstand",
    kind: "bakery",
    access: "walk-up",
    county: "Pasco",
    city: "Land O Lakes",
    address: "15212 State Rd 52",
    zip: null,
    lat: 28.32992426173,
    lng: -82.567301738758,
    pinQuality: "exact",
    hours: "7 days 8:30am–7:30pm",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["sweets", "honey", "eggs", "cake", "produce", "bread"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "calico-kreations",
    name: "Calico Kreations",
    kind: "bakery",
    access: "walk-up",
    county: "Pasco",
    city: "Port Richey",
    address: "7417 Bougainville Dr",
    zip: null,
    lat: 28.312183841966,
    lng: -82.692736707694,
    pinQuality: "exact",
    hours: "7 days 12:30pm–dark",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["cookies", "cake", "bread", "jam", "goat products", "cheese", "drinks"],
    notes: "Source list spelled Bougenville.",
    sourceNotes: null,
    featured: false,
  },
  {
    id: "freedom-sourdough",
    name: "Freedom Sourdough",
    kind: "bakery",
    access: "walk-up",
    county: "Pasco",
    city: "New Port Richey",
    address: "5346 Main St #103",
    zip: null,
    lat: 28.250164079936,
    lng: -82.725903703159,
    pinQuality: "exact",
    hours: "Mon–Sat 8am–6pm, Sun 12pm–4pm",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["bread", "cupcakes", "sweets", "preserves"],
    notes: "Storefront hours.",
    sourceNotes: null,
    featured: false,
  },
  {
    id: "pink-hen-pantry",
    name: "Pink Hen Pantry",
    kind: "bakery",
    access: "walk-up",
    county: "Pasco",
    city: "New Port Richey",
    address: "6038 Apple Snail Ave",
    zip: null,
    lat: 28.213742117844,
    lng: -82.714069962346,
    pinQuality: "exact",
    hours: "Sat/Sun 9am–5pm",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["bread", "cookies", "honey", "cupcakes"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "sweet-nothings",
    name: "Sweet Nothings",
    kind: "bakery",
    access: "preorder",
    county: "Pasco",
    city: "New Port Richey",
    address: null,
    zip: null,
    lat: 28.25195,
    lng: -82.7195,
    pinQuality: "approx",
    hours: "Msg for preorder",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["cake", "cupcakes", "sweets"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "the-baking-soldier",
    name: "The Baking Soldier",
    kind: "bakery",
    access: "walk-up",
    county: "Pinellas",
    city: "Tarpon Springs",
    address: "11 N Pinellas Ave",
    zip: null,
    lat: 28.146371222131,
    lng: -82.75669692701,
    pinQuality: "exact",
    hours: "Wed–Sat 10am–6pm",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["bread", "sweets", "cake"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "moonberry-mercantile",
    name: "Moonberry Mercantile",
    kind: "bakery",
    access: "walk-up",
    county: "Pinellas",
    city: "Tarpon Springs",
    address: "101 W Court St",
    zip: null,
    lat: 28.145564741403,
    lng: -82.757650126251,
    pinQuality: "exact",
    hours: "Mon–Sat 11am–6pm, Sun 11am–4pm",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["bread", "meat", "eggs", "honey", "soap", "produce", "milk"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "renardo-family-produce",
    name: "Renardo Family Produce",
    kind: "bakery",
    access: "walk-up",
    county: "Pinellas",
    city: "Tarpon Springs",
    address: "630 S Pinellas Ave",
    zip: null,
    lat: 28.141021310783,
    lng: -82.756673922881,
    pinQuality: "exact",
    hours: "Mon–Sat 9am–6pm, Sun 10am–5pm",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["produce", "fruit", "bread", "cheese", "honey", "milk"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "sugar-fatties",
    name: "Sugar Fatties",
    kind: "bakery",
    access: "check-page",
    county: "Pinellas",
    city: "Tarpon Springs",
    address: "801 Peninsula Rd",
    zip: null,
    lat: 28.137618828109,
    lng: -82.777012649714,
    pinQuality: "exact",
    hours: "Markets and porch pickup — check page",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["cookies", "cake", "sweets"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "the-flour-garden",
    name: "The Flour Garden",
    kind: "bakery",
    access: "walk-up",
    county: "Pinellas",
    city: "Tarpon Springs",
    address: "470 S Florida Ave",
    zip: null,
    lat: 28.139927512524,
    lng: -82.781309886688,
    pinQuality: "exact",
    hours: "Sat 8am–dark",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["cookies", "bread", "bagels"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "gabrielle-s-bakery",
    name: "Gabrielle's Bakery",
    kind: "bakery",
    access: "walk-up",
    county: "Pinellas",
    city: "Tarpon Springs",
    address: "1924 Whispering Way",
    zip: null,
    lat: 28.123720280976,
    lng: -82.773337311934,
    pinQuality: "exact",
    hours: "Sat 12pm–sellout, preorders",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["cookies", "bread", "cupcakes", "sweets"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "franklin-s-family-bakery",
    name: "Franklin's Family Bakery",
    kind: "bakery",
    access: "preorder",
    county: "Pinellas",
    city: "Tarpon Springs",
    address: null,
    zip: null,
    lat: 28.150183,
    lng: -82.75455,
    pinQuality: "approx",
    hours: "Msg for preorder",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["bread", "bagels", "cookies", "cupcakes"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "melina-s-fresh-squeezed",
    name: "Melina's Fresh Squeezed",
    kind: "stand",
    access: "preorder",
    county: "Pinellas",
    city: "Tarpon Springs",
    address: null,
    zip: null,
    lat: 28.15235,
    lng: -82.75655,
    pinQuality: "approx",
    hours: "Msg for preorder",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["juice", "fruit"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "dipped-by-demi",
    name: "Dipped By Demi",
    kind: "bakery",
    access: "preorder",
    county: "Pinellas",
    city: "Tarpon Springs",
    address: null,
    zip: null,
    lat: 28.142517,
    lng: -82.751383,
    pinQuality: "approx",
    hours: "Msg for preorder",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["chocolate", "sweets", "cake"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "the-cracked-pot-bakery",
    name: "The Cracked Pot Bakery",
    kind: "bakery",
    access: "preorder",
    county: "Pinellas",
    city: "Tarpon Springs",
    address: null,
    zip: null,
    lat: 28.1536,
    lng: -82.752383,
    pinQuality: "approx",
    hours: "Msg for preorder",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["bread", "cookies", "sweets"],
    notes: "Phone 727-271-1297",
    sourceNotes: null,
    featured: false,
  },
  {
    id: "avery-farms",
    name: "Avery Farms",
    kind: "bakery",
    access: "walk-up",
    county: "Hernando",
    city: "Spring Hill",
    address: "1458 Heritage Ave",
    zip: null,
    lat: 28.45755991099,
    lng: -82.618543953251,
    pinQuality: "exact",
    hours: "Sat/Sun 8am–8pm",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["cookies", "cake", "eggs", "produce", "bread"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "red-s-farmstand",
    name: "Red's Farmstand",
    kind: "bakery",
    access: "walk-up",
    county: "Hernando",
    city: "Spring Hill",
    address: "6353 Alderwood St",
    zip: null,
    lat: 28.460259274486,
    lng: -82.611371709139,
    pinQuality: "exact",
    hours: "Sat 8am–6pm, Sun 8am–5pm",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["bread", "cupcakes", "cookies", "candles", "preserves"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "magnolia-s-farmstand",
    name: "Magnolia's Farmstand",
    kind: "bakery",
    access: "walk-up",
    county: "Hernando",
    city: "Spring Hill",
    address: "8029 Lullwater Ave",
    zip: null,
    lat: 28.444956321888,
    lng: -82.589895846126,
    pinQuality: "exact",
    hours: "Wed–Fri 8am–9pm",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["cookies", "cake", "bread"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "ace-harvest-farmstand-microbakery",
    name: "ACE Harvest Farmstand & Microbakery",
    kind: "bakery",
    access: "walk-up",
    county: "Hernando",
    city: "Spring Hill",
    address: "9124 El Camino St",
    zip: null,
    lat: 28.465812491779,
    lng: -82.571267896563,
    pinQuality: "exact",
    hours: "Fri/Sat 10am–8pm, Sun 10am–5pm",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["honey", "cupcakes", "bread", "cookies", "sweets"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "crunchy-dough-co",
    name: "Crunchy Dough Co.",
    kind: "bakery",
    access: "preorder",
    county: "Hernando",
    city: "Spring Hill",
    address: "Mariner Blvd & Landover",
    zip: null,
    lat: 28.4689,
    lng: -82.5315,
    pinQuality: "approx",
    hours: "Msg for preorder",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["cupcakes", "bread", "cookies"],
    notes: "Intersection listing.",
    sourceNotes: null,
    featured: false,
  },
  {
    id: "the-neighbor-s-market",
    name: "The Neighbor's Market",
    kind: "market",
    access: "walk-up",
    county: "Hernando",
    city: "Spring Hill",
    address: "2033 Bishop Rd",
    zip: null,
    lat: 28.462211511154,
    lng: -82.559082383355,
    pinQuality: "exact",
    hours: "Fri–Sun 8:30am–5pm",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["cookies", "cake", "cupcakes", "honey", "bread"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "momma-bear-s-roadside-stand",
    name: "Momma Bear's Roadside Stand",
    kind: "bakery",
    access: "walk-up",
    county: "Hernando",
    city: "Spring Hill",
    address: "12234 Villa Rd",
    zip: null,
    lat: 28.494041782789,
    lng: -82.522093481163,
    pinQuality: "exact",
    hours: "Thu–Sat 9am–8pm, Sun 9am–3pm",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["bread", "eggs", "cupcakes"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "the-cozy-coop",
    name: "The Cozy Coop",
    kind: "bakery",
    access: "walk-up",
    county: "Hernando",
    city: "Spring Hill",
    address: "14162 Segovia St",
    zip: null,
    lat: 28.478425422142,
    lng: -82.49188486187,
    pinQuality: "exact",
    hours: "Sat/Sun 9am–6pm",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["bread", "cupcakes", "cookies", "preserves"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "cozy-cookie-co",
    name: "Cozy Cookie Co",
    kind: "bakery",
    access: "walk-up",
    county: "Hernando",
    city: "Spring Hill",
    address: "Trollman St & Hawthorne Rd",
    zip: null,
    lat: 28.478817,
    lng: -82.518333,
    pinQuality: "approx",
    hours: "Reportedly 7 days 8am–7:30pm — confirm",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["cookies", "cake"],
    notes: "Hours marked uncertain on source list.",
    sourceNotes: null,
    featured: false,
  },
  {
    id: "wild-roots-homestead",
    name: "Wild Roots Homestead",
    kind: "bakery",
    access: "walk-up",
    county: "Hernando",
    city: "Spring Hill",
    address: "2291 Euclid Ave",
    zip: null,
    lat: 28.46814004853,
    lng: -82.49283474266,
    pinQuality: "exact",
    hours: "Wed/Sat/Sun 9:30am–4pm, Mon 10am–4pm",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["bread", "cookies", "drinks"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "two-swans-co",
    name: "Two Swans Co.",
    kind: "bakery",
    access: "walk-up",
    county: "Hernando",
    city: "Spring Hill",
    address: "4234 Goldfoil Rd",
    zip: null,
    lat: 28.471983,
    lng: -82.51875,
    pinQuality: "approx",
    hours: "Sat/Sun 10am–8pm",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["eggs", "honey", "cookies", "coffee", "plants"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "vontro-funny-farm-homestead-market",
    name: "Vontro Funny Farm Homestead & Market",
    kind: "market",
    access: "check-page",
    county: "Pasco",
    city: "New Port Richey",
    address: null,
    zip: null,
    lat: 28.241283,
    lng: -82.725917,
    pinQuality: "approx",
    hours: "Check page for details",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["eggs", "meat", "poultry"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "crust-and-crumbs-microbakery",
    name: "Crust and Crumbs Microbakery",
    kind: "bakery",
    access: "preorder",
    county: "Pasco",
    city: "New Port Richey",
    address: null,
    zip: null,
    lat: 28.2437,
    lng: -82.7225,
    pinQuality: "approx",
    hours: "Msg for address / preorder",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["bread", "bagels", "cupcakes", "sweets"],
    notes: "Markets around NPR.",
    sourceNotes: null,
    featured: false,
  },
  {
    id: "coco-and-crumb-by-nancy",
    name: "Coco and Crumb by Nancy",
    kind: "bakery",
    access: "preorder",
    county: "Pasco",
    city: "Port Richey",
    address: null,
    zip: null,
    lat: 28.265117,
    lng: -82.72175,
    pinQuality: "approx",
    hours: "Baked to order — message",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["bread"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "olive-and-sage-bakes",
    name: "Olive and Sage Bakes",
    kind: "bakery",
    access: "preorder",
    county: "Pasco",
    city: "New Port Richey",
    address: null,
    zip: null,
    lat: 28.242117,
    lng: -82.71375,
    pinQuality: "approx",
    hours: "Msg for preorder, also markets",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["bread", "cookies"],
    notes: "Downtown NPR markets.",
    sourceNotes: null,
    featured: false,
  },
  {
    id: "le-petite-delice",
    name: "Le Petite Delice",
    kind: "market",
    access: "markets",
    county: "Pasco",
    city: "New Port Richey",
    address: null,
    zip: null,
    lat: 28.250367,
    lng: -82.723917,
    pinQuality: "approx",
    hours: "Currently on summer break",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["bread", "pastries"],
    notes: "Seasonal closure noted on source list.",
    sourceNotes: null,
    featured: false,
  },
  {
    id: "triple-treats",
    name: "Triple Treats",
    kind: "stand",
    access: "preorder",
    county: "Pasco",
    city: "Land O Lakes",
    address: "Lake Padgett East",
    zip: null,
    lat: 28.222067,
    lng: -82.45435,
    pinQuality: "approx",
    hours: "Sun 9am–5pm — msg for address",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["sweets"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "cole-s-farm-market",
    name: "Cole's Farm Market",
    kind: "market",
    access: "walk-up",
    county: "Pasco",
    city: "Hudson",
    address: "15127 US Hwy 19",
    zip: null,
    lat: 28.376689419843,
    lng: -82.681522968114,
    pinQuality: "exact",
    hours: "Tue/Thu 11am–5:30pm, Wed/Fri/Sat 10am–5:30pm",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["produce", "fruit", "honey"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "sandhill-sourdough",
    name: "Sandhill Sourdough",
    kind: "bakery",
    access: "preorder",
    county: "Pasco",
    city: "Hudson",
    address: "Briar Oaks Neighborhood",
    zip: null,
    lat: 28.363567,
    lng: -82.686067,
    pinQuality: "approx",
    hours: "Msg for preorder",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["bread", "cookies"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "rural-desserts",
    name: "Rural Desserts",
    kind: "bakery",
    access: "walk-up",
    county: "Pasco",
    city: "Hudson",
    address: "17230 East Rd",
    zip: null,
    lat: 28.408752954766,
    lng: -82.600572314063,
    pinQuality: "exact",
    hours: "7 days 7:30am–dark",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["cookies", "cake", "sweets"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "hudsons-happy-ass-farmstand",
    name: "Hudsons Happy Ass Farmstand",
    kind: "bakery",
    access: "walk-up",
    county: "Pasco",
    city: "Hudson",
    address: "13838 Oakwood Dr",
    zip: null,
    lat: 28.380870386141,
    lng: -82.586863609611,
    pinQuality: "exact",
    hours: "Wed–Sun 7am–7pm",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["bread", "pastries", "honey", "coffee", "eggs"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "our-family-farm-agricultural",
    name: "Our Family Farm Agricultural",
    kind: "bakery",
    access: "walk-up",
    county: "Pasco",
    city: "Hudson",
    address: "13120 Hudson Ave",
    zip: null,
    lat: 28.360935560455,
    lng: -82.596614673112,
    pinQuality: "exact",
    hours: "Sat–Sun 8am–6pm",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["eggs", "cookies", "bread", "donuts", "honey", "soap", "plants"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "xoxo-sourdough",
    name: "XOXO Sourdough",
    kind: "bakery",
    access: "check-page",
    county: "Hernando",
    city: "Brooksville",
    address: null,
    zip: null,
    lat: 28.560633,
    lng: -82.395817,
    pinQuality: "approx",
    hours: "Check page for pop-ups",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["bread", "cookies", "cupcakes"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "three-dog-farm",
    name: "Three Dog Farm",
    kind: "bakery",
    access: "walk-up",
    county: "Hernando",
    city: "Brooksville",
    address: "6444 California St",
    zip: "34604",
    lat: 28.526435437318,
    lng: -82.458557564766,
    pinQuality: "exact",
    hours: "7 days 8:30am–5:30pm",
    phone: "(508) 745-6171",
    email: null,
    website: null,
    facebook: "https://www.facebook.com/p/Three-Dog-Farm-100087740490790/",
    instagram: null,
    products: ["produce", "cookies", "preserves", "plants", "tea"],
    notes: null,
    sourceNotes: "Facebook about page + MapQuest hours.",
    featured: true,
  },
  {
    id: "the-porch-at-southern-sun-mill",
    name: "The Porch at Southern Sun Mill",
    kind: "bakery",
    access: "walk-up",
    county: "Hernando",
    city: "Brooksville",
    address: "19426 Lake Lindsey Rd",
    zip: null,
    lat: 28.629183664405,
    lng: -82.400767317185,
    pinQuality: "exact",
    hours: "Sat 9am–6pm, Sun 10am–6pm",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["cookies", "bread", "sweets"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "dusk-family-farm",
    name: "Dusk Family Farm",
    kind: "stand",
    access: "walk-up",
    county: "Hernando",
    city: "Brooksville",
    address: "13164 Harrison St",
    zip: null,
    lat: 28.555382840547,
    lng: -82.509207660525,
    pinQuality: "exact",
    hours: "7 days dawn–dusk",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["eggs", "honey"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "crumbs-and-roses-bakery-stand",
    name: "Crumbs and Roses Bakery Stand",
    kind: "bakery",
    access: "walk-up",
    county: "Hernando",
    city: "Brooksville",
    address: "13476 Flemington Rd",
    zip: null,
    lat: 28.623987789391,
    lng: -82.509908399653,
    pinQuality: "exact",
    hours: "Sat 9am–4pm",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["bread", "cookies"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "hidden-view-farm",
    name: "Hidden View Farm",
    kind: "stand",
    access: "walk-up",
    county: "Hernando",
    city: "Brooksville",
    address: "25646 Halsey Rd",
    zip: null,
    lat: 28.507832644881,
    lng: -82.311308598833,
    pinQuality: "exact",
    hours: "Sat/Sun 9am–3pm",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["produce"],
    notes: "Product icons were cut off on the source screenshot.",
    sourceNotes: null,
    featured: false,
  },
  {
    id: "kiki-s-coop",
    name: "Kiki's Coop",
    kind: "stand",
    access: "check-page",
    county: "Hernando",
    city: "Weeki Wachee",
    address: "12245 Sunshine Grove Rd",
    zip: null,
    lat: 28.603671688422,
    lng: -82.502801842916,
    pinQuality: "exact",
    hours: "Check page for hours",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["plants", "sweets"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "cada-farms",
    name: "Cada Farms",
    kind: "bakery",
    access: "walk-up",
    county: "Hernando",
    city: "Weeki Wachee",
    address: "12367 Filbert Rd",
    zip: "34614",
    lat: 28.605545605343,
    lng: -82.513429860727,
    pinQuality: "exact",
    hours: "7 days 10am–5pm",
    phone: "(352) 553-4646",
    email: "contact@cadafarms.com",
    website: "https://www.cadafarms.com/",
    facebook: "https://www.facebook.com/cadafarms/",
    instagram: null,
    products: ["bread", "donuts", "eggs"],
    notes: "Source list said Filbert Dr; farm site uses Filbert Rd.",
    sourceNotes: "cadafarms.com + Yelp phone.",
    featured: false,
  },
  {
    id: "the-big-blue-box-bakery",
    name: "The Big Blue Box Bakery",
    kind: "bakery",
    access: "check-page",
    county: "Hernando",
    city: "Weeki Wachee",
    address: "11522 Marvelwood Rd",
    zip: null,
    lat: 28.59615026132,
    lng: -82.519571115729,
    pinQuality: "exact",
    hours: "Check page for schedule",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["bread", "cookies", "produce"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "ohana-sips-sweets",
    name: "Ohana Sips & Sweets",
    kind: "bakery",
    access: "walk-up",
    county: "Hernando",
    city: "Weeki Wachee",
    address: "12220 Pine Finch Ave",
    zip: null,
    lat: 28.602633527781,
    lng: -82.522838982889,
    pinQuality: "exact",
    hours: "Sat/Sun 9am–3pm",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["drinks", "sweets", "bread", "cookies"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "toripops",
    name: "Toripops",
    kind: "bakery",
    access: "walk-up",
    county: "Hernando",
    city: "Weeki Wachee",
    address: "13695 Downy Woodpecker Rd",
    zip: null,
    lat: 28.661531773956,
    lng: -82.501581357528,
    pinQuality: "exact",
    hours: "Sat/Sun 10am–8:30pm",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["cake", "sweets"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "farmer-s-daughter",
    name: "Farmer's Daughter",
    kind: "bakery",
    access: "walk-up",
    county: "Hernando",
    city: "Brooksville",
    address: "17250 Benes Roush Rd",
    zip: null,
    lat: 28.440972916568,
    lng: -82.443427224454,
    pinQuality: "exact",
    hours: "Fri/Sat 10am–dark",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["bread", "cookies", "eggs", "flowers"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "the-silo-on-ayers",
    name: "The Silo on Ayers",
    kind: "bakery",
    access: "walk-up",
    county: "Hernando",
    city: "Brooksville",
    address: "19297 Ayers Rd",
    zip: null,
    lat: 28.451536850556,
    lng: -82.411215410123,
    pinQuality: "exact",
    hours: "Sat 10am–3pm",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["beef", "eggs", "bread", "honey", "produce"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "everything-sourdough-organic-farmstand",
    name: "Everything Sourdough Organic Farmstand",
    kind: "bakery",
    access: "walk-up",
    county: "Hernando",
    city: "Brooksville",
    address: "1442 Culbreath Rd",
    zip: null,
    lat: 28.456755323209,
    lng: -82.370656827372,
    pinQuality: "exact",
    hours: "Sat/Sun 8am–sellout",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["bread"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "sweet-liberty-pastures-farmstand",
    name: "Sweet Liberty Pastures Farmstand",
    kind: "bakery",
    access: "walk-up",
    county: "Pasco",
    city: "Dade City",
    address: "16548 Bellamy Brothers Blvd",
    zip: null,
    lat: 28.39520347696,
    lng: -82.370480621876,
    pinQuality: "exact",
    hours: "Fri–Sun 8am–4pm",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["bread", "cookies", "cake"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "hancock-homestead-farmstand",
    name: "Hancock Homestead Farmstand",
    kind: "bakery",
    access: "walk-up",
    county: "Hernando",
    city: "Brooksville",
    address: "146 Hancock Lake Rd",
    zip: null,
    lat: 28.436685523633,
    lng: -82.348252415808,
    pinQuality: "exact",
    hours: "Fri/Sat 9am–5pm",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["bread", "cake", "cookies", "honey", "flowers"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "encanto-bakery",
    name: "Encanto Bakery",
    kind: "bakery",
    access: "walk-up",
    county: "Hernando",
    city: "Brooksville",
    address: "3431 Saturn Rd",
    zip: null,
    lat: 28.484838491969,
    lng: -82.406091504989,
    pinQuality: "exact",
    hours: "Sat–Sun 9:30am–sellout",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["bread", "cookies"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "shevah-flower-farm",
    name: "Shevah Flower Farm",
    kind: "stand",
    access: "seasonal",
    county: "Hernando",
    city: "Brooksville",
    address: "16173 Snow Memorial Hwy",
    zip: null,
    lat: 28.660235378366,
    lng: -82.359891143257,
    pinQuality: "exact",
    hours: "Closed for summer",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["flowers", "honey"],
    notes: "Seasonal closure on source list.",
    sourceNotes: null,
    featured: false,
  },
  {
    id: "whisked-away",
    name: "Whisked Away",
    kind: "bakery",
    access: "walk-up",
    county: "Hernando",
    city: "Brooksville",
    address: "Charlick Rd & Spring Lake Hwy",
    zip: null,
    lat: 28.559217,
    lng: -82.3944,
    pinQuality: "approx",
    hours: "Fri 3pm–dark, Sat/Sun 9am–dark",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["bread", "cake", "cupcakes", "cookies", "sweets"],
    notes: "Intersection listing.",
    sourceNotes: null,
    featured: false,
  },
  {
    id: "two-k-farms",
    name: "Two K Farms",
    kind: "bakery",
    access: "walk-up",
    county: "Hernando",
    city: "Brooksville",
    address: "4347 Eva Lou Dr",
    zip: null,
    lat: 28.497975575591,
    lng: -82.36092052458,
    pinQuality: "exact",
    hours: "Fri–Sun 10am–dark",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["eggs", "honey", "cookies", "cake", "bread", "milk", "soap", "goat products"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "hinkley-s-farm-stand",
    name: "Hinkley's Farm Stand",
    kind: "bakery",
    access: "walk-up",
    county: "Hernando",
    city: "Brooksville",
    address: "24050 Cortez Blvd",
    zip: null,
    lat: 28.536844022586,
    lng: -82.34226563433,
    pinQuality: "exact",
    hours: "Fri 1pm–dark, Sat/Sun 9am–dark",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["bread", "cookies", "cupcakes"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "beasley-farms",
    name: "Beasley Farms",
    kind: "stand",
    access: "walk-up",
    county: "Hernando",
    city: "Brooksville",
    address: "10137 Preston Rd",
    zip: "34601",
    lat: 28.573378494972,
    lng: -82.319619861028,
    pinQuality: "exact",
    hours: "Sat–Thu 8am–5pm",
    phone: "(352) 799-6752",
    email: null,
    website: null,
    facebook: "https://www.facebook.com/p/Beasley-Farms-100064428470174/",
    instagram: null,
    products: ["eggs", "produce", "flowers"],
    notes: "Closed Friday per source list.",
    sourceNotes: "Yelp + FDACS u-pick listing + Facebook hours.",
    featured: true,
  },
  {
    id: "kindred-made",
    name: "Kindred Made",
    kind: "bakery",
    access: "seasonal",
    county: "Hernando",
    city: "Spring Hill",
    address: "12578 Spring Hill Dr",
    zip: null,
    lat: 28.46601070717,
    lng: -82.51315441241,
    pinQuality: "exact",
    hours: "Reopening Sept 12",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["bread", "cookies"],
    notes: "Reopening date from source list.",
    sourceNotes: null,
    featured: false,
  },
  {
    id: "lucy-lou-s-sweet-shop",
    name: "Lucy Lou's Sweet Shop",
    kind: "bakery",
    access: "walk-up",
    county: "Hernando",
    city: "Spring Hill",
    address: "1229 Carlton St",
    zip: null,
    lat: 28.452411909547,
    lng: -82.490994839847,
    pinQuality: "exact",
    hours: "7 days 9am–8pm",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["cookies", "cupcakes", "cake", "drinks"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "simply-sweet-cottage-bakery",
    name: "Simply Sweet Cottage Bakery",
    kind: "bakery",
    access: "walk-up",
    county: "Hernando",
    city: "Spring Hill",
    address: "1212 Carlton St",
    zip: null,
    lat: 28.451906752186,
    lng: -82.490860963071,
    pinQuality: "exact",
    hours: "Fri–Sun till dark",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["cookies", "bread", "eggs", "cake", "sweets"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "the-stray-hearth",
    name: "The Stray Hearth",
    kind: "bakery",
    access: "walk-up",
    county: "Hernando",
    city: "Spring Hill",
    address: "18153 Monteverde Dr",
    zip: null,
    lat: 28.422016128784,
    lng: -82.543379631733,
    pinQuality: "exact",
    hours: "Sat 9am–9pm, Sun 10am–6pm",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["cookies", "cake", "pastries", "bread", "sweets"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "the-sweet-tooth-shop",
    name: "The Sweet Tooth Shop",
    kind: "bakery",
    access: "walk-up",
    county: "Hernando",
    city: "Spring Hill",
    address: "18023 Oxenham Ave",
    zip: null,
    lat: 28.425571010306,
    lng: -82.518004627553,
    pinQuality: "exact",
    hours: "Sat/Sun 7:30am–6:30pm",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["cookies", "bread", "cupcakes"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "sweet-thang-brookies-and-cookies",
    name: "Sweet Thang Brookies and Cookies",
    kind: "bakery",
    access: "walk-up",
    county: "Hernando",
    city: "Spring Hill",
    address: "18155 Scooter Ct",
    zip: null,
    lat: 28.4213894284,
    lng: -82.562834954429,
    pinQuality: "exact",
    hours: "7 days 8am–dark",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["cookies", "sweets", "honey"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
  {
    id: "moore-market",
    name: "Moore Market",
    kind: "market",
    access: "walk-up",
    county: "Hernando",
    city: "Spring Hill",
    address: "18325 Kelly Rd",
    zip: "34610",
    lat: 28.424297826269,
    lng: -82.578291278321,
    pinQuality: "exact",
    hours: "7 days 8am–dark",
    phone: null,
    email: null,
    website: null,
    facebook: "https://www.facebook.com/p/Moore-Market-61575298954921/",
    instagram: null,
    products: ["eggs", "bread", "cookies", "honey"],
    notes: null,
    sourceNotes: "Facebook page + Spring Hill Neighbors group.",
    featured: true,
  },
  {
    id: "dough-rae-me-sourdough-co",
    name: "Dough-Rae-Me Sourdough Co",
    kind: "bakery",
    access: "preorder",
    county: "Hernando",
    city: "Spring Hill",
    address: "Mosquero Rd & Northcliffe Blvd",
    zip: null,
    lat: 28.478567,
    lng: -82.5265,
    pinQuality: "approx",
    hours: "Msg for preorder",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["bread", "cupcakes", "cookies"],
    notes: "Intersection listing.",
    sourceNotes: null,
    featured: false,
  },
  {
    id: "arrow-in-hand",
    name: "Arrow in Hand",
    kind: "market",
    access: "markets",
    county: "Hernando",
    city: "Spring Hill",
    address: null,
    zip: null,
    lat: 28.4699,
    lng: -82.52675,
    pinQuality: "approx",
    hours: "Markets and online",
    phone: null,
    email: null,
    website: null,
    facebook: null,
    instagram: null,
    products: ["spices", "tea"],
    notes: null,
    sourceNotes: null,
    featured: false,
  },
];
