/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as StandIdRouteImport } from './routes/stand.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiTilesKindZXYRouteImport } from './routes/api/tiles.$kind.$z.$x.$y'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StandIdRoute = StandIdRouteImport.update({
  id: '/stand/$id',
  path: '/stand/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTilesKindZXYRoute = ApiTilesKindZXYRouteImport.update({
  id: '/api/tiles/$kind/$z/$x/$y',
  path: '/api/tiles/$kind/$z/$x/$y',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/stand/$id': typeof StandIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/tiles/$kind/$z/$x/$y': typeof ApiTilesKindZXYRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/stand/$id': typeof StandIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/tiles/$kind/$z/$x/$y': typeof ApiTilesKindZXYRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/stand/$id': typeof StandIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/tiles/$kind/$z/$x/$y': typeof ApiTilesKindZXYRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/stand/$id'
    | '/api/auth/$'
    | '/api/tiles/$kind/$z/$x/$y'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/stand/$id'
    | '/api/auth/$'
    | '/api/tiles/$kind/$z/$x/$y'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/stand/$id'
    | '/api/auth/$'
    | '/api/tiles/$kind/$z/$x/$y'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  StandIdRoute: typeof StandIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTilesKindZXYRoute: typeof ApiTilesKindZXYRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stand/$id': {
      id: '/stand/$id'
      path: '/stand/$id'
      fullPath: '/stand/$id'
      preLoaderRoute: typeof StandIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tiles/$kind/$z/$x/$y': {
      id: '/api/tiles/$kind/$z/$x/$y'
      path: '/api/tiles/$kind/$z/$x/$y'
      fullPath: '/api/tiles/$kind/$z/$x/$y'
      preLoaderRoute: typeof ApiTilesKindZXYRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  StandIdRoute: StandIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTilesKindZXYRoute: ApiTilesKindZXYRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
